on:
  - pull_request
  - push

name: CI

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php:
          - "8.1"
          - "8.2"
          - "8.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_mysql
          coverage: pcov
          ini-values: assert.exception=1, zend.assertions=1

      - name: Install composer dependencies
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Run tests with phpunit
        run: vendor/bin/phpunit
        env:
          DB_DSN: 'mysql:host=127.0.0.1;charset=utf8mb4'
          DB_USER: 'root'
          DB_PASSWORD: 'root'
